Repository googleapis/java-iot, pull requests merged in 2020-06, with the labels that each got.

#152 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#144 fix: restore GAPIC v2 retry configs
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerClient.java
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerSettings.java
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/package-info.java
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/DeviceManagerStub.java
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/DeviceManagerStubSettings.java
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/GrpcDeviceManagerStub.java
  google-cloud-iot/src/test/java/com/google/cloud/iot/v1/DeviceManagerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#155 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#154 chore: regenerate with updated protoc
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/BindDeviceToGatewayRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/CreateDeviceRegistryRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/CreateDeviceRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeleteDeviceRegistryRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeleteDeviceRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/Device.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceConfig.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceCredential.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceRegistry.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/DeviceState.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/EventNotificationConfig.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GatewayAuthMethod.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GatewayConfig.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GatewayListOptions.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GatewayType.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GetDeviceRegistryRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GetDeviceRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/HttpConfig.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/HttpState.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceConfigVersionsRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceConfigVersionsResponse.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceRegistriesRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceRegistriesResponse.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceStatesRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDeviceStatesResponse.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDevicesRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDevicesResponse.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/LogLevel.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ModifyCloudToDeviceConfigRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/MqttConfig.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/MqttState.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyCertificate.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyCertificateFormat.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyCredential.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/PublicKeyFormat.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/RegistryCredential.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/SendCommandToDeviceRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/StateNotificationConfig.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UnbindDeviceFromGatewayRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UpdateDeviceRegistryRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/UpdateDeviceRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/X509CertificateDetails.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#157 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#159 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#164 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#170 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#174 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-iot/pom.xml
  grpc-google-cloud-iot-v1/pom.xml
  pom.xml
  proto-google-cloud-iot-v1/pom.xml
Labels: cla: yes

#175 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#184 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
