Repository googleapis/java-iot, pull requests merged in 2021-05, with the labels that each got.

#444 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: none

#445 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudiot, automerge, cla: yes

#450 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#452 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#453 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#459 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#461 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#464 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#422 chore: add blunderbuss config to cloud iot label
  .github/blunderbuss.yml
Labels: api: cloudiot, cla: yes
