Repository googleapis/java-iot, pull requests merged in 2021-02, with the labels that each got.

#348 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#352 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudiot, cla: yes, context: partial

#354 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  LICENSE
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#355 fix: update repo name
  .kokoro/release/publish_javadoc11.cfg
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#342 docs: add iot team as code owner
  .github/CODEOWNERS
Labels: api: cloudiot, cla: yes

#360 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#361 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#353 docs: add fieldMask format clarification to avoid misunderstandings.
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerClient.java
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/package-info.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GetDeviceRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/GetDeviceRequestOrBuilder.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDevicesRequest.java
  proto-google-cloud-iot-v1/src/main/java/com/google/cloud/iot/v1/ListDevicesRequestOrBuilder.java
  proto-google-cloud-iot-v1/src/main/proto/google/cloud/iot/v1/device_manager.proto
  proto-google-cloud-iot-v1/src/main/proto/google/cloud/iot/v1/resources.proto
  synth.metadata
Labels: api: cloudiot, cla: yes, context: full

#365 build(java): update autorelease script
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: partial

#366 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#369 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#368 chore: update gapic-generator-java to 0.0.20
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/GrpcDeviceManagerStub.java
  google-cloud-iot/src/test/java/com/google/cloud/iot/v1/DeviceManagerClientTest.java
  google-cloud-iot/src/test/java/com/google/cloud/iot/v1/MockDeviceManagerImpl.java
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#370 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#371 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#372 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#374 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/gapic_metadata.json
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#379 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#380 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#388 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes
