Repository googleapis/java-iot, pull requests merged in 2021-06, with the labels that each got.

#475 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#482 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#485 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes

#486 chore: exclude blunderbuss from synth
  synth.py
Labels: api: cloudiot, automerge, cla: yes

#489 chore: release gapic-generator-java v1.0.11
  google-cloud-iot/src/test/java/com/google/cloud/iot/v1/DeviceManagerClientTest.java
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#490 chore: release gapic-generator-java v1.0.12
  google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/DeviceManagerStubSettings.java
  synth.metadata
Labels: api: cloudiot, cla: yes, context: full

#494 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudiot, automerge, cla: yes
